
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
    command: flask run --host=0.0.0.0 --port=8080
    depends_on:
      - mysql

  mysql:

    command:
      --default-authentication-plugin=mysql_native_password --init-file=/docker-entrypoint-initdb.d/init.sql
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=sstipassword
      - MYSQL_ROOT_HOST:'%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
