services:
  app:
    build: .
    ports:
      - 32043:5000
    volumes:
      - ./flag.txt:/flag.txt
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G
